language: java
sudo: false
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: triberay
    token:
      secure: vaTOVEEN6lT5cJmW6S+FESDtgjH3cmm48ez/uXCG2DyU0iMfBrs9UqJAkNsreefIfsP+gJYNY3X+O/gWF/eMzGbSpsPH84pFT3ize4uDP+yRDOM4DOcqjsJ+UA5AxvqKKX7uqIQbyJE0z3v10oodHgJG41qyQ7ek4lnqeZMmpMQL8RJ5hjXic2fJ98m1Tu+djh6ZdCR2wMlq9E2IuSYhLSFWjlIzMQZJyv1jDORhyzd/cqrdDcqCMxfEQ6+6YF5U5i9EXJYGmjs74MoysCQUYjA5sOhJb2bNzncwa6IfLGNupdOFo1oyvLnXYOmNf0lG/O52dvuitWv7kbJseahBanVrMh/CFYDQFBbbDvuGDTZEP8LZvwJC4g2ONea1Czel6V68KeXFZ4G+UE2eDFyRhQaltVhpuFosnd/0fXeMPAE1lkiTo8Ga7Ryj/NGqxnyLgSEEs6NMlNOJu54qy+zypv4/lfuCkTRQWBPGDQHLfOrEi9TRbliXE0JZXDQvzsvEpgl+VEn4BXgIqrbw0NZr6lLVdxW5vkHKBCAHSb69Ln2Dk/pQwDlmVGo5KvNsNaUKDE18mdVXE7/1+Lj+DML5OtX0ruI9YK8OdPKoT/VGwRHLP7JRayT7tSPyjhAaKBEfBjGPTribzr8jVcl1ZaXlIrG0ypQiHvZOOBSUZ7DV44o=
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  slack:
    rooms:
      secure: rzIU3MJpOrLaZzJfsH9XTSG2TrDqTAphaJE+TGvuImIBxsOZvrfqZPbVA5CyoxisPuK46xNLwgJ/dDBR6Wu3S/NkJzGAR2t/CskJ1MMvHtRY/7RbzcxA3x+YLprIV0xmvgWOtcco3/UoafxXmOv0OFtjAvYftoM45MDkO0lWOqKbTeWOhPoTMJRlOeTS/5LXdqUDOwk0xjJvmGL98Mhktsce4JtpHkdv1lFYJgHFBBAnGsh5wNKVACc0uNUQOFbTB7reTMhKTdlieRJaif5mmX8YJodEwo3Poxeo6hDjcRjxnsyvRB1qDvpJLJ14kctlH6F0fmI7dv/qzmCwilMTLMRsfxeObpww6EMc6RCs3b/xFN5GGDJ2GOt2BnzTgqTIkcBLbZIzrcZLJJoxnl9UHCsGgKxT4bYVgz7F1MtEGnC3cbxGP1Ru3NEwbYTb9CjkQZxUh/89AEPMsoAXy+Rl6ix1G97T6MmpN8fFE+2gRf0nKzSOmFXCo2r7FJ5HSFMgKogxjOT5S9ik457nYyRcR5FHx6gtfDsmaiLHBdJqOMMjYW8v93DUQ2sBAn65p3GchXQqkMLiNF3LxaRZ4c2EH+DcvB/ZzMs6VvY2F8INmil2j9YcPna9EVrsGF5C0uJ8IRaujz1Okn45B4hoHHrMN3GxOCRcQ1MjEKcQhYr5VCs=
